jdk:
- oraclejdk8

addons:
  chrome: stable
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - npm install && node_modules/brunch/bin/brunch build --production
  - mix compile
  - mix phx.digest
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
